### ISSUE TITLE
Support TLS/SRTP

### ISSUE THREAD

**Issue by LubosD** [LubosD/twinkle#18]
Twinkle supports only ZRTP, but not TLS/SRTP.

http://support.privatewave.com/display/WS/SDES

**Comment by LubosD** [comment]
http://tools.ietf.org/html/rfc4568
Mini certificate format: http://lists.digium.com/pipermail/asterisk-dev/2005-December/017388.html

**Comment by LubosD** [comment]
TLS is more or less complete, but switching between UDP/TCP and TLS at runtime is still problematic:

````
#0  0x00007ffff7bc9834 in pthread_mutex_lock () from /lib64/libpthread.so.0
#1  0x000000000086e027 in t_mutex::lock (this=0x8) at /home/lubos/Projects/twinkle/src/threads/mutex.cpp:52
#2  0x00000000007808b8 in t_user::get_tls_ca_cert (this=0x0) at /home/lubos/Projects/twinkle/src/user.cpp:1350
#3  0x0000000000858fc2 in t_socket_tcp_tls::t_socket_tcp_tls (this=0x7fff400016e0, user=0x0, 
    hostname="\270\315\021\001\000\000\000\000\000\313\377\377\377\177\000\000\000\000\000\000\000\000\000\000P\233\001L\377\177\000\000\260\254_a\377\177\000\000\336\bm\000\000\000\000\000\300\254_a\377\177\000\000\270\227\001L\377\177\000\000Ь_a\377\177\000\000\210r]\000\000\000\000\000P\233\001L\377\177\000\000\230\224\001L\377\177\000\000\360\254_a\377\177\000\000\322M\177\000\000\000\000\000\270\227\001L\377\177\000\000\230\224\001L\377\177\000\000\020\255_a\377\177\000\000\346K\177\000\000\000\000\000\230\224\001L\377\177\000\000\230\224\001L\377\177\000\000\060\255_a\377\177\000\000\fL\177\000\000\000\000\000أ\001L\377\177\000\000\230\224\001L\377\177\000\000P\255_a\377\177\000\000"...)
    at /home/lubos/Projects/twinkle/src/sockets/socket.cpp:388
#4  0x000000000073fb02 in send_sip_tcp (event=0x7fff4c00c380, transport_type="tls_tcp") at /home/lubos/Projects/twinkle/src/sender.cpp:248
#5  0x0000000000741cbe in sender_loop (arg=0x0) at /home/lubos/Projects/twinkle/src/sender.cpp:560
#6  0x00007ffff7bc7314 in start_thread () from /lib64/libpthread.so.0
#7  0x00007ffff2bb33ad in clone () from /lib64/libc.so.6
````
Next step after fixing this is SRTP.

**Comment by sp31415t1** [comment]
Hi,
It has been added to milestone 2.0.0 in June 2015.
It's still open.
I would like to know if that feature is supposed to be present in the last release ?
I cannot report a bug to my distrib after having seen that feature request is still open.
Regards,

**Comment by LubosD** [comment]
@sp31415t1 This issue is still open and version 2.0.0 hasn't been released yet, so no, it's not in the last release, sorry.

**Comment by lachesis** [comment]
Is this still unsupported? Would it be feasible to get TLS support working or build 2.0.0beta locally?
